[app] 
    env = 'dev'

[mysql]
    addr = 'localhost:3306'
    user = 'root'
    db_name = 'gateway_teach'
    password = '123456'

[redis]
    addr = 'localhost:6379'
    password = ''
    prefix = ''
    db = 1
